import type { Metadata } from "next";
import "@/globals.css";
import { Pirata_One } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Header from '@/_components/header';

const blackletter = Pirata_One({
  subsets: ['latin'],
  weight: "400",
  variable: "--blackletter"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={`${blackletter.variable} antialiased`}
        >
          <AntdRegistry>
            <Header/>
            {children}
          </AntdRegistry>
        </body>
    </html>
  );
}
